enrichment_services:
  otx_api_key: 
  otx_ipv4_indicators_url: https://otx.alienvault.com/api/v1/indicators/IPv4
  otx_domain_indicators_url: https://otx.alienvault.com/api/v1/indicators/domain

default_names:
  image_name: pydetective_sandbox_container
  image_tag: pydetective_sandbox_container:latest
  tcpdump_image_tag: tcpdump:latest
  db_table_name: pydetective_results

file_paths:
  installation_script: setup.sh
  rules_folder_path: rules
  static_rules_folder_path: rules/static_rules
  dynamic_rules_folder_path: rules/dynamic_rules
  logging_path: logs/pydetective.log
  output_folder_path: out
  static_result_path: out/static_result.json
  syscalls_result_path: out/syscalls_result.json
  network_result_path: out/network_result.json
  post_install_result_path: out/deepscan_result.txt
  network_output_path: out/tcpdump_output.pcap
  syscalls_output_path: out/sysdig_output.scap
  evaluation_output_path: out/evaluation_result.json
  sandbox_folder_path: sandbox
  sample_package_path: sandbox/sample_malicious_package
  downloaded_package_path: sandbox/downloaded_package
  archives_path: sandbox/downloaded_package/archives
  extracted_path: sandbox/downloaded_package/extracted
  falco_config_path: config/falco.yaml
  container_dir_path: /app
  pypi_projects_dependency_path: pyproject.toml
  config_folder_path: config
  src_folder_path: src
  deepscan_output_path: /app/deepscan_result.txt
  database_folder_path: /database
  database_path: /database/pydetective.db
  tcpdump_path: /src/tcpdump

ignored_ips:
  - 151.101.0.223
  - 151.101.192.223
  - 151.101.128.223
  - 151.101.64.223
  - 172.17.0.2
  - 2a04:4e42::223
  - 192.168.0.1
  - 2a04:4e42:200::223
  - 2a04:4e42:400::223
  - 2a04:4e42:600::223
  - 2a04:4e42:800::223

ignored_domains:
  - pypi.org
  - files.pythonhosted.org
  - dualstack.python.map.fastly.net

ignored_syscalls:
  - not (proc.cmdline contains 'clamscan -i -r')
  - not (proc.cmdline contains 'pip install --break-system-packages /app/archives/')

thresholds:
  MAX_TOLERATED_LOW_PRIORITY_NETWORK: 1
  MAX_TOLERATED_HIGH_PRIORITY_NETWORK: 0
  MAX_TOLERATED_LOW_PRIORITY_SYSCALLS: 1
  MAX_TOLERATED_HIGH_PRIORITY_SYSCALLS: 0
  MAX_TOLERATED_LOW_PRIORITY_STATIC: 1
  MAX_TOLERATED_HIGH_PRIORITY_STATIC: 0
  MAX_TOLERATED_HIGH_PRIORITY_POST_INSTALL: 0
