enrichment_services:
  otx_api_key: 
  otx_ipv4_indicators_url: https://otx.alienvault.com/api/v1/indicators/IPv4
  otx_domain_indicators_url: https://otx.alienvault.com/api/v1/indicators/domain

containers:
  image_name: pydetective_sandbox_container
  image_tag: pydetective_sandbox_container:latest

file_paths:
  installation_script: setup.sh
  rules_folder_path: rules
  static_rules_folder_path: rules/static_rules
  dynamic_rules_folder_path: rules/dynamic_rules
  logging_path: logs/pydetective.log
  output_folder_path: out
  static_result_path: out/static_result.json
  syscalls_result_path: out/syscalls_result.json
  network_result_path: out/network_result.json
  post_install_result_path: out/post_install_result.json
  network_output_path: out/tcpdump_output.pcap
  syscalls_output_path: out/sysdig_output.scap
  evaluation_output_path: out/evaluation_result.json
  sandbox_folder_path: sandbox
  sample_package_path: sandbox/sample_malicious_package
  downloaded_package_path: sandbox/downloaded_package
  archives_path: sandbox/downloaded_package/archives
  archives_local_path: sandbox/downloaded_package/archives/package
  extracted_path: sandbox/downloaded_package/extracted
  extracted_local_path: sandbox/downloaded_package/extracted/package
  falco_config_path: config/falco.yaml
  container_dir_path: /app
  pypi_projects_dependency_path: pyproject.toml
  config_folder_path: config
  src_folder_path: src
  deepscan_output_path: /app/deepscan_output.txt

ignored_ips:
  - 151.101.0.223
  - 151.101.192.223
  - 151.101.128.223

ignored_domains:
  - pypi.org
  - files.pythonhosted.org
  - dualstack.python.map.fastly.net

ignored_syscalls:
  - not (proc.cmdline contains 'clamscan -i -r')
  - not (proc.cmdline contains 'pip install --break-system-packages /app/archives/package')

thresholds:
  MAX_FREQUENCY: 10 # percentage
  MAX_DURATION: 14000 # seconds
  MAX_HTTP_SIZE: 50000 # bytes
  MAX_SUBDOMAIN_LENGTH: 30 # chars
