# FROM ubuntu:latest

# # Set non-interactive mode to avoid prompts during installation
# ENV DEBIAN_FRONTEND=noninteractive

# # Update package list and install dependencies (including surl)
# RUN apt-get update && \
#     apt-get install -y \
#     python3 \
#     python3-pip \
#     tcpdump \
#     curl 

FROM python:3.12-slim